name: persona
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.1=py37_0
  - astor=0.8.0=py37_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h1de35cc_1001
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - cycler=0.10.0=py37_0
  - freetype=2.9.1=hb4e5f40_0
  - gast=0.2.2=py37_0
  - grpcio=1.16.1=py37h044775b_1
  - h5py=2.9.0=py37h3134771_0
  - hdf5=1.10.4=hfa1e0ec_0
  - intel-openmp=2019.4=233
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py37_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.8.0=hd9629dc_0
  - markdown=3.1.1=py37_0
  - matplotlib=3.1.0=py37h54f8f79_0
  - mkl=2019.4=233
  - mkl-service=2.0.2=py37h1de35cc_0
  - mkl_fft=1.0.14=py37h5e564d8_0
  - mkl_random=1.0.2=py37h27c97d8_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.16.4=py37hacdab7b_0
  - numpy-base=1.16.4=py37h6575580_0
  - openssl=1.1.1c=h1de35cc_1
  - pip=19.2.2=py37_0
  - protobuf=3.8.0=py37h0a44026_0
  - pyparsing=2.4.2=py_0
  - python=3.7.4=h359304d_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py37h1de35cc_0
  - readline=7.0=h1de35cc_5
  - scipy=1.3.1=py37h1410ff5_0
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=ha441bb4_0
  - tensorboard=1.14.0=py37h80053f4_0
  - tensorflow=1.14.0=mkl_py37h085be34_0
  - tensorflow-base=1.14.0=mkl_py37h5a24fda_0
  - tensorflow-estimator=1.14.0=py_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py37h1de35cc_0
  - werkzeug=0.15.5=py_0
  - wheel=0.33.4=py37_0
  - wrapt=1.11.2=py37h1de35cc_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - fasttext==0.9.1
    - joblib==0.13.2
    - nltk==3.4.5
    - pandas==0.25.1
    - pybind11==2.3.0
    - scikit-learn==0.21.3
    - sklearn==0.0
prefix: /Users/hang/anaconda3/envs/persona

